[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.4
datadir=D:/StudyMate/mysql_data
port=3306
skip-log-bin
tmpdir=D:/StudyMate/mysql_data/tmp
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

[client]
port=3306
default-character-set=utf8mb4
