"""init schema: users/study_tasks/study_records/ai_analysis/login_tickets

Revision ID: 0b7f891a6d8e
Revises: 
Create Date: 2026-07-26 17:40:22.569009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7f891a6d8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_unionid'), ['unionid'], unique=False)

    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=32), nullable=False, comment='daily_summary/plan_optimization/qa'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='分析输入'),
    sa.Column('output_data', sa.Text(), nullable=True, comment='分析结果'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_user_id'), ['user_id'], unique=False)

    op.create_table('login_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket', sa.String(length=64), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_tickets_openid'), ['openid'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_tickets_ticket'), ['ticket'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('study_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='科目：数学/英语/政治/408'),
    sa.Column('content', sa.String(length=512), nullable=False, comment='任务内容'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='结束时间'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='pending/done/cancelled'),
    sa.Column('plan_source', sa.String(length=16), nullable=True, comment='manual/excel/json/pdf'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_tasks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('study_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='学习时长（秒）'),
    sa.Column('record_type', sa.String(length=16), nullable=True, comment='pomodoro/countdown/focus'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['study_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_records_user_id'))

    op.drop_table('study_records')
    with op.batch_alter_table('study_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_tasks_date'))

    op.drop_table('study_tasks')
    with op.batch_alter_table('login_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_tickets_ticket'))
        batch_op.drop_index(batch_op.f('ix_login_tickets_openid'))

    op.drop_table('login_tickets')
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_user_id'))

    op.drop_table('ai_analysis')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_unionid'))
        batch_op.drop_index(batch_op.f('ix_users_openid'))

    op.drop_table('users')
    # ### end Alembic commands ###
